### ISSUE TITLE
On new tellonym

### ISSUE THREAD

**Issue by piotrusieeeek** [PatchByte/pyhton-tellonym-api#1]
Is it possible to get an on_new_tell webhook event? So whenever there's a new tellonym we can do something with it?

**Comment by PatchByte** [comment]
I will take a look!

**Comment by PatchByte** [comment]
Tellonym has cloudflare and you have to find a good interval for the requests but there is a chance that cloudflare bans you.

**Comment by piotrusieeeek** [comment]
btw, where did you find the docs for the tellonym api? Can't seem to find them

**Comment by PatchByte** [comment]
Oh there are no docs.
These are just the requests if you go to a tellonym's user website
