### ISSUE TITLE
"logging" error

### ISSUE THREAD

**Issue by cloutjs** [PatchByte/pyhton-tellonym-api#3]
Hello, I'm not sure if this project is discontinued or something but I still have a question.

I got this error while trying the example code: TypeError: __init__() missing 1 required positional argument: 'logging'

Maybe someone can help me with that ❤️

**Comment by PatchByte** [comment]
Hey sorry i thought i already removed all debugging functions just do: TellonymApi(false)!

**Comment by PatchByte** [comment]
False*

**Comment by PatchByte** [comment]
```python
import tellonym_api

api = tellonym_api.TellonymApi(False)

user = api.GetUser("[your user]")
if user.IsProfileFound() == True:
    #profile is existing
else:
    #profile isnt existing!
```

**Comment by cloutjs** [comment]
Working, thank you so much!
