### ISSUE TITLE
I cant get tells

### ISSUE THREAD

**Issue by Karpfen11** [PatchByte/pyhton-tellonym-api#4]
if try to print the tell i get this list:

[<tellonym_api.TellonymTell object at 0x0000017739087940>, <tellonym_api.TellonymTell object at 0x00000177390878E0>, <tellonym_api.TellonymTell object at 0x0000017739087880>, <tellonym_api.TellonymTell object at 0x0000017739087820>, <tellonym_api.TellonymTell object at 0x00000177390877C0>, <tellonym_api.TellonymTell object at 0x0000017739087760>, <tellonym_api.TellonymTell object at 0x0000017739087550>, <tellonym_api.TellonymTell object at 0x0000017739087220>, <tellonym_api.TellonymTell object at 0x0000017739087700>, <tellonym_api.TellonymTell object at 0x000001773909E8E0>, <tellonym_api.TellonymTell object at 0x000001773909E940>, <tellonym_api.TellonymTell object at 0x000001773909E6D0>, <tellonym_api.TellonymTell object at 0x000001773909E370>, <tellonym_api.TellonymTell object at 0x000001773909E1F0>, <tellonym_api.TellonymTell object at 0x000001773909E760>, <tellonym_api.TellonymTell object at 0x000001773909E3A0>, <tellonym_api.TellonymTell object at 0x000001773909E790>, <tellonym_api.TellonymTell object at 0x000001773909E0D0>, <tellonym_api.TellonymTell object at 0x0000017737E4FFA0>, <tellonym_api.TellonymTell object at 0x0000017737E4F130>, <tellonym_api.TellonymTell object at 0x0000017737598DC0>, <tellonym_api.TellonymTell object at 0x000001773909E8B0>, <tellonym_api.TellonymTell object at 0x000001773909E730>, <tellonym_api.TellonymTell object at 0x000001773909E9A0>, <tellonym_api.TellonymTell object at 0x000001773909EA00>, <tellonym_api.TellonymTell object at 0x000001773909EA60>, <tellonym_api.TellonymTell object at 0x000001773909EAC0>, <tellonym_api.TellonymTell object at 0x000001773909EB20>, <tellonym_api.TellonymTell object at 0x000001773909EB80>, <tellonym_api.TellonymTell object at 0x000001773909EBE0>, <tellonym_api.TellonymTell object at 0x000001773909EC40>, <tellonym_api.TellonymTell object at 0x000001773909ECA0>, <tellonym_api.TellonymTell object at 0x000001773909ED00>, <tellonym_api.TellonymTell object at 0x000001773909ED60>, <tellonym_api.TellonymTell object at 0x000001773909EDC0>, <tellonym_api.TellonymTell object at 0x000001773909EE20>, <tellonym_api.TellonymTell object at 0x000001773909EE80>, <tellonym_api.TellonymTell object at 0x000001773909EEE0>, <tellonym_api.TellonymTell object at 0x000001773909EF40>, <tellonym_api.TellonymTell object at 0x000001773909EFA0>, <tellonym_api.TellonymTell object at 0x0000017739087040>, <tellonym_api.TellonymTell object at 0x00000177390870A0>, <tellonym_api.TellonymTell object at 0x0000017739087100>, <tellonym_api.TellonymTell object at 0x0000017739087160>, <tellonym_api.TellonymTell object at 0x00000177390871C0>]

**Comment by PatchByte** [comment]
tellonym_api.TellonymTell is a object
example code
```python
objX = ....
# objX is a tellonym_api.TellonymTell

print(objX.answer)
# Prints out the answer
```
